# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('wip', models.GenericIPAddressField(unique=True, verbose_name='\u5916\u7f51IP')),
                ('lip', models.GenericIPAddressField(unique=True, verbose_name='\u5185\u7f51IP')),
                ('system_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('ssh_port', models.IntegerField(default=22, verbose_name='ssh\u7aef\u53e3')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u786c\u76d8')),
                ('instance_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5b9e\u4f8bID')),
                ('buy_time', models.DateTimeField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5230\u671f\u65f6\u95f4')),
                ('online_status', models.SmallIntegerField(choices=[(0, '\u4e0a\u7ebf'), (1, '\u4e0b\u7ebf')], verbose_name='\u72b6\u6001')),
                ('serverid', models.IntegerField(blank=True, null=True, verbose_name='ServerID')),
                ('gameid', models.IntegerField(blank=True, null=True, verbose_name='GameID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'assets',
                'verbose_name': '\u8d44\u4ea7',
                'verbose_name_plural': '\u8d44\u4ea7',
                'permissions': set([('can_connect_asset', '\u53ef\u4ee5\u8fde\u63a5\u7ec8\u7aef'), ('can_view_asset', '\u53ef\u4ee5\u67e5\u770b\u8d44\u4ea7'), ('can_monitor_asset', '\u53ef\u4ee5\u76d1\u63a7\u7ec8\u7aef'), ('can_kill_asset', '\u53ef\u4ee5\u5173\u95ed\u7ec8\u7aef'), ('can_delete_asset', '\u53ef\u4ee5\u5220\u9664\u8d44\u4ea7'), ('can_add_asset', '\u53ef\u4ee5\u6dfb\u52a0\u8d44\u4ea7'), ('can_change_asset', '\u53ef\u4ee5\u4fee\u6539\u8d44\u4ea7')]),
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u7ec4\u540d')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('servers', models.ManyToManyField(to='asset.Assets')),
            ],
            options={
                'db_table': 'hostgroups',
                'verbose_name': '\u4e3b\u673a\u7ec4',
                'verbose_name_plural': '\u4e3b\u673a\u7ec4',
                'permissions': (('can_add_hostgroup', '\u53ef\u4ee5\u6dfb\u52a0\u4e3b\u673a\u7ec4'), ('can_change_hostgroup', '\u53ef\u4ee5\u4fee\u6539\u4e3b\u673a\u7ec4\u4fe1\u606f'), ('can_delete_hostrgroup', '\u53ef\u4ee5\u5220\u9664\u4e3b\u673a\u7ec4'), ('can_view_hostgroup', '\u53ef\u4ee5\u67e5\u770b\u4e3b\u673a\u7ec4')),
            },
        ),
        migrations.CreateModel(
            name='HostUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u540d\u79f0')),
                ('auth_method', models.CharField(choices=[('ssh-password', 'SSH/ Password'), ('ssh-key', 'SSH/KEY')], help_text='\u5982\u679c\u9009\u62e9SSH/KEY\uff0c\u8bf7\u786e\u4fdd\u4f60\u7684\u79c1\u94a5\u6587\u4ef6\u5df2\u5728settings.py\u4e2d\u6307\u5b9a', max_length=16, verbose_name='\u7c7b\u578b')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(blank=True, help_text='\u5982\u679cauth_method\u9009\u62e9\u7684\u662fSSH/KEY,\u90a3\u6b64\u5904\u4e0d\u9700\u8981\u586b\u5199..', max_length=64, null=True, verbose_name='\u5bc6\u7801')),
                ('key', models.TextField(blank=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('width', models.PositiveIntegerField(default=1024, verbose_name='width')),
                ('height', models.PositiveIntegerField(default=768, verbose_name='height')),
                ('dpi', models.PositiveIntegerField(default=96, verbose_name='dpi')),
            ],
            options={
                'db_table': 'hostusers',
                'verbose_name': '\u8fdc\u7a0b\u7528\u6237',
                'verbose_name_plural': '\u8fdc\u7a0b\u7528\u6237',
                'permissions': (('can_add_hostuser', '\u53ef\u4ee5\u6dfb\u52a0\u670d\u52a1\u5668\u7528\u6237\u4fe1\u606f'), ('can_change_hostuser', '\u53ef\u4ee5\u4fee\u6539\u670d\u52a1\u5668\u7528\u6237\u4fe1\u606f'), ('can_delete_hostuser', '\u53ef\u4ee5\u5220\u9664\u670d\u52a1\u5668\u7528\u6237\u4fe1\u606f'), ('can_view_hostuser', '\u53ef\u4ee5\u67e5\u770b\u670d\u52a1\u5668\u7528\u6237\u4fe1\u606f')),
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='\u673a\u623f\u540d')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('utime', models.DateTimeField(auto_now=True)),
                ('servers', models.ManyToManyField(to='asset.Assets')),
            ],
            options={
                'db_table': 'idc',
                'verbose_name': '\u673a\u623f',
                'verbose_name_plural': '\u673a\u623f',
                'permissions': set([('can_delete_idc', '\u53ef\u4ee5\u5220\u9664\u673a\u623f'), ('can_view_idc', '\u53ef\u4ee5\u67e5\u770b\u673a\u623f\u4fe1\u606f'), ('can_change_idc', '\u53ef\u4ee5\u4fee\u6539\u673a\u623f\u4fe1\u606f'), ('can_add_idc', '\u53ef\u4ee5\u6dfb\u52a0\u673a\u623f')]),
            },
        ),
        migrations.AlterUniqueTogether(
            name='hostusers',
            unique_together=set([('auth_method', 'password', 'username')]),
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.HostUsers', verbose_name='\u7cfb\u7edf\u7528\u6237'),
        ),
    ]
