# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'\xe5\xb7\xa5\xe5\x85\xb7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('tool_script', models.TextField(blank=True, null=True, verbose_name=b'\xe8\x84\x9a\xe6\x9c\xac')),
                ('tool_run_type', models.CharField(choices=[(b'shell', b'shell'), (b'python', b'python'), (b'yml', b'yml')], max_length=24, verbose_name=b'\xe8\x84\x9a\xe6\x9c\xac\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('comment', models.TextField(blank=True, null=True, verbose_name=b'\xe5\xb7\xa5\xe5\x85\xb7\xe8\xaf\xb4\xe6\x98\x8e')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'Tools',
                'verbose_name': '\u5de5\u5177',
                'verbose_name_plural': '\u5de5\u5177',
            },
        ),
        migrations.CreateModel(
            name='ToolsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(unique=True, verbose_name=b'\xe4\xbb\xbb\xe5\x8a\xa1ID')),
                ('add_user', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'db_table': 'ToolsResults',
                'verbose_name': '\u4efb\u52a1',
                'verbose_name_plural': '\u4efb\u52a1',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name=b'\xe5\x8f\x98\xe9\x87\x8f\xe7\xbb\x84\xe5\x90\x8d\xe5\xad\x97')),
                ('desc', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('vars', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name=b'\xe5\x8f\x98\xe9\x87\x8f')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('assets', models.ManyToManyField(blank=True, related_name='asset', to='asset.Assets', verbose_name=b'\xe5\x85\xb3\xe8\x81\x94\xe8\xb5\x84\xe4\xba\xa7')),
            ],
            options={
                'db_table': 'Variable',
                'verbose_name': '\u53d8\u91cf\u7ec4',
                'verbose_name_plural': '\u53d8\u91cf\u7ec4',
            },
        ),
    ]
